
/*

* File:   autom.c

* Author: james

*

* Created on April 18, 2024, 12:41 PM

*/
 
 
#include "xc.h"

#include "system.h"
#include "pump.h"
#include "autom.h"


void init_ax(){
    
    
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 

        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 

    
     delay_ms(DELAY_AUTOM);
   

    
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX_BIELLE,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX_BIELLE,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX_BIELLE,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX_BIELLE,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX_BIELLE,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX_BIELLE,SANS_ATTENTE); // on monte le rack 


    
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE); 

  
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);

    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE); 

    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);


    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE); 


    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);

    
    delay_ms(DELAY_AUTOM);
}


void test_pump()

{

     // Example usage

    turnOnPump_ARM1();

    turnOnPump_ARM2();

    turnOnPump_ARM3();

    turnOnPump_STOCK1();

    turnOnPump_STOCK2();

    turnOnPump_STOCK3();


    delay_ms(10000);

    turnOffPump_ARM1();

    turnOffPump_ARM2();

    turnOffPump_ARM3();

    turnOffPump_STOCK1();

    turnOffPump_STOCK2();

    turnOffPump_STOCK3();


    delay_ms(1000);

 
    

}
 
 
void start_turb(bool A1, bool A2, bool A3){

    

        for (int i=500;i<TURB_MAX;i++){
             
             if(A1){
             
                P1DC1 = (uint16_t) i; 
            }
            
             if(A2){
             
                P1DC2 = (uint16_t) i; 
            }
            
             if(A3){
             
                P1DC3 = (uint16_t) i; 
            }
             

            
            delay_ms(DELAY_ACCEL_TURB); // or 1 .? dont remerber

        } 

      

       //readSensors();


}

void safe_stop_turb(){

    // to test
    
    if( P1DC1>500 ) {
    
        for (P1DC1;P1DC1<500;--P1DC1){
            delay_ms(1);
        }
    }
    
    
    
    if( P1DC2>500 ) {
    
        for (P1DC2;P1DC2<500;--P1DC2){
            delay_ms(1);
        }
    }
    

    if( P1DC3>500 ) {
    
        for (P1DC3;P1DC3<500;--P1DC3){
            delay_ms(1);
        }
    }
    
    
       
    if( P2DC1>500 ) {
    
        for (P2DC1;P2DC1<500;--P2DC1){
            delay_ms(1);
        }
    }
        
   
    

}
 
void stop_turb(bool A1, bool A2, bool A3){

   // printf("CUT TURBINE \n");

       for (int i=TURB_MAX;i>499;--i){

             if(A1){
             
                P1DC1 = (uint16_t) i; 
            }
            
             if(A2){
             
                P1DC2 = (uint16_t) i; 
            }
            
             if(A3){
             
                P1DC3 = (uint16_t) i; 
            }

             
            delay_ms(DELAY_ACCEL_TURB);
       }

      //  printf("TURBINE OFF\n");

        // readSensors();

}
 
 
void open_servo(){

    //printf("OPENING SERVO\n");

    P2DC1 = (uint16_t) 3000;  
      
    //printf("SERVO OPEN\n");

}
 
 
void close_servo(){

   //printf("CLOSING SERVO\n");

    P2DC1 = (uint16_t) 1000;  

    //printf("SERVO CLOSE\n");
}

/*
    if(A1) function1();

    if(A2) ....
 
    if(A3) ....
 * 
 * 
 *  
 
    if(A1)

    if(A2) 
 
    if(A3)
 * 
    */
    
 
//angle_AX12 (uint8_t ID,  uint16_t position, uint16_t vitesse, uint8_t ATTENTE )
void stock_plant(bool A1, bool A2, bool A3){
    
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE); // on monte le rack 
    
    if(A1){
        turnOnPump_ARM1();
 
        angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);  
        angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
        
        
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE);

        turnOnPump_STOCK1();
        
    }
    
    if(A2) {
        turnOnPump_ARM2();

        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);

        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
    
        turnOnPump_STOCK2();
    }
    
    if(A3) {
        
        turnOnPump_ARM3();
        
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);

        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 


        turnOnPump_STOCK3();
    }
    //init pçs ax 
  
    delay_ms(DELAY_AUTOM);

        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 

        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE);
        
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE); 
        

    
    
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 

    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE);
    
    delay_ms(DELAY_AUTOM);
    
    if(A1){
        
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 

      
    }

    if(A2){
        
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 

    }
 
    if(A3){
        
        angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
        angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 

    
    }

    delay_ms(DELAY_AUTOM);

    
    if(A1){
                
        turnOffPump_ARM1();
     

    }

    if(A2){
        
        turnOffPump_ARM2();
     

    }
 
    if(A3){
        
        turnOffPump_ARM3();  
     

    }
    
    

  
           

  

}


void destock_plant(bool A1, bool A2, bool A3){

    //init_ax();
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP1,POS_TOP1_MID,VIT_AX,SANS_ATTENTE); 

    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 
    angle_AX12(ID_TOP2,POS_TOP2_MID,VIT_AX,SANS_ATTENTE); 

    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_MID,VIT_AX,SANS_ATTENTE);

    
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 

    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 
    angle_AX12(ID_BIELLE,POS_BIELLE_DOWN,VIT_AX,SANS_ATTENTE); // on monte le rack 

    
    delay_ms(DELAY_AUTOM);

    if(A1){

      turnOnPump_ARM1(); 
      angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_STOCK,VIT_AX,SANS_ATTENTE); 

    }

    if(A2){

      turnOnPump_ARM2(); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_STOCK,VIT_AX,SANS_ATTENTE); 

    }

    if(A3){

      turnOnPump_ARM3(); 
      angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_STOCK,VIT_AX,SANS_ATTENTE); 

    }

      delay_ms(DELAY_AUTOM);
      //delay_ms(DELAY_AUTOM);


      
    if(A1){

      turnOffPump_STOCK1();
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE); 

      
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);



    }

    if(A2){

      turnOffPump_STOCK2();
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE); 
      

      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);

      

      

    }

    if(A3){

      turnOffPump_STOCK3();
      
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 
      angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE); 


      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);

      
      
      
      

    }
      delay_ms(DELAY_AUTOM);


    if(A1){

      turnOffPump_ARM1(); 
    }

    if(A2){

      turnOffPump_ARM2(); 
    }  

    if(A3){

      turnOffPump_ARM3(); 
    }      

}
 
 
void readSensors() {

    printf("%d_%d_%d:%d_%d_%d", SENSOR_PRESENCE1, SENSOR_PRESENCE2, SENSOR_PRESENCE3, SENSOR_COLOR1, SENSOR_COLOR2, SENSOR_COLOR3);
    
}

void hands_up(){
    
    
    turnOnPump_ARM1();
    turnOnPump_ARM2();
    turnOnPump_ARM3();
     
   
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE);

    angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP1,POS_TOP1_DEPOSE,VIT_AX,SANS_ATTENTE);

    angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP2,POS_TOP2_DEPOSE,VIT_AX,SANS_ATTENTE);

    angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_DEPOSE,VIT_AX,SANS_ATTENTE);

    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);

    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);

    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    
    
}



void hands_down(){
    
    
    turnOnPump_ARM1();
    turnOnPump_ARM2();
    turnOnPump_ARM3();
     
   
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_UP,VIT_AX,SANS_ATTENTE);
    
    
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM1,POS_BTM1_GRAB,VIT_AX,SANS_ATTENTE);

    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM2,POS_BTM2_GRAB,VIT_AX,SANS_ATTENTE);

    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BTM3,POS_BTM3_GRAB,VIT_AX,SANS_ATTENTE);
    
    
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP1,POS_TOP1_GRAB,VIT_AX,SANS_ATTENTE);
    
    
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP2,POS_TOP2_GRAB,VIT_AX,SANS_ATTENTE);
   

    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_TOP3,POS_TOP3_GRAB,VIT_AX,SANS_ATTENTE);

    

    
    
}


void depose_jard(bool A1, bool A2, bool A3){
 
    
    angle_AX12(ID_BIELLE,POS_BIELLE_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DEPOSE,VIT_AX,SANS_ATTENTE);
    angle_AX12(ID_BIELLE,POS_BIELLE_DEPOSE,VIT_AX,SANS_ATTENTE);
    
    delay_ms(DELAY_AUTOM);
    
    if(A1){
        
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM1,POS_BTM1_DEPOSE,VIT_AX,SANS_ATTENTE);
    
      turnOffPump_ARM1();   
      
      
      
    }
    
    if(A2){
        
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM2,POS_BTM2_DEPOSE,VIT_AX,SANS_ATTENTE);
     
      turnOffPump_ARM2();
      
      
    }
    
    if(A3){
        
      
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      angle_AX12(ID_BTM3,POS_BTM3_DEPOSE,VIT_AX,SANS_ATTENTE);
      
      turnOffPump_ARM3();
      
    }
    
    
    delay_ms(DELAY_AUTOM);
    
    // put hands up function
    
    
  
}






